version: 0.2

phases:
  install:
    commands:
      # install node 12
      - cinst nodejs.install
       # install npm 
      - npm i -g npm 
  pre_build:
    commands:
      # install depenecies...
      - npm install
  build:
    commands:
      # build......
      - npm run build
artifacts:
    files:
      - '**/*'
    discard-paths: no     
    base-directory: dist